baseURL: "https://theduckparty.github.io/"
title: "DuckParty's Blog"
theme: PaperMod

paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - JSON

menu:
  main:
    - name: Tags
      url: tags/
      weight: 1
    - name: Search
      url: search/
      weight: 2
    - name: About
      url: about/
      weight: 3

params:
  env: production
  description: "Blog made from Notion with Hugo, hosted on GitHub Pages"
  keywords: [blog, hugo, notion, github]
  defaultTheme: dark
  disableThemeToggle: false
  disableSpecial1stPost: true
  ShowCodeCopyButtons: true
  ShowToc: false

  mainSections:
    - posts

  profileMode:
    enabled: false
    title: Blog template
    # imageUrl: "avatar.png"
    # imageTitle: ""
    # imageWidth: 120
    # imageHeight: 120
    subtitle: "Blog made from Notion with Hugo and GitHub Pages"

  socialIcons:
    - name: github
      url: "https://github.com/Malsius/blog-template"

  # label:
  #   text: ""
  #   icon: "avatar.png"
  #   iconHeight: 30
  
  # assets:
  #   favicon: "favicons/favicon.ico"
  #   favicon16x16:  "favicons/favicon-16x16.png"
  #   favicon32x32:  "favicons/favicon-32x32.png"
  #   apple_touch_icon:  "favicons/apple-touch-icon.png"
  #   safari_pinned_tab:  "favicons/favicon.ico"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
